
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);
INSERT INTO pledges (amount,user_id,project_id) VALUES (200,1,1);

INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('project_x','party',10000,'2017-03-18','2017-11-11');

INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
INSERT INTO users (name, age) VALUES ('user_x',24);
